# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')

setup(
    long_description=readme,
    name='eff',
    version='1.0.0',
    python_requires='>=3.6',
    project_urls={"homepage": "https://github.com/orsinium-labs/eff"},
    author='Gram',
    author_email='gram@orsinium.dev',
    classifiers=['License :: OSI Approved :: MIT License'],
    packages=['eff'],
    package_dir={"": "."},
    package_data={},
    install_requires=[],
)
